sudo: required

services:
 - docker

language: go

go:
 - "1.10.x"

install:
 - go get -t ./...

before_script:
 - go vet ./...

deploy:
    provider: script
    script: bash build/docker/docker_push.sh
    on:
      branch: master
