go_import_path: github.com/thourfor/stocktopus

install:
- git clone https://github.com/thorfour/stocktopus.git
- go get -t -d ./...

language: go

go:
- 1.8

script:
 - make all && make clean
 - go test -v ./...
