version: 2
jobs:
  buildandtest:
    working_directory: /go/src/github.com/thorfour/stocktopus
    docker:
     - image: circleci/golang:1.14
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: build
          command: | 
            make circle-ci-bin
            make circle-ci-test
  deploy:
    working_directory: /go/src/github.com/thorfour/stocktopus
    docker:
     - image: circleci/golang:1.14
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: push docker
          command: |
<<<<<<< HEAD
            make circle-ci-bin
            make docker
=======
            make circle-ci-docker
>>>>>>> 1678b4279c9edb5062df9d4b1ffc718ba7b2f278
            make push

workflows:
  version: 2
  pre-commit:
    jobs:
      - buildandtest
  post-commit:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
