---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: stocktopus
spec:
  selector:
    app: prometheus
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stocktopus
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
      matchLabels:
        app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: quay.io/prometheus/prometheus:v2.10.0
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
        ports:
          - containerPort: 9090
        volumeMounts:
          - name: prom-conf-vol
            mountPath: /etc/prometheus
      volumes:
         - name:  prom-conf-vol
           configMap:
             defaultMode: 420
             name: prom-conf
---
apiVersion: v1
kind: ConfigMap
metadata: 
  namespace: stocktopus
  name: prom-conf
  labels:
      name: prom-conf
data:
  prometheus.yml: |-
    scrape_configs:
      - job_name: "stocktopus"
        scrape_interval: 15s

        metrics_path: "/metrics"

        static_configs:
            - targets: ['stocktopus-green-srv.stocktopus.svc.cluster.local:8080']
            - targets: ['stocktopus-blue-srv.stocktopus.svc.cluster.local:8080']
